import Head from "next/head";
import {Link, Box} from "@mui/material";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            width: 300,
            height: 300,
            backgroundColor: "primary.dark",
            "&:hover": {
              opacity: [0.9, 0.8, 0.7],
            },
          }}
        >
          <Link href="/sign-up-form">sign up for free</Link>
        </Box>
      </main>
    </div>
  );
}
