import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {Link} from "@mui/material";
import {Container} from "@mui/material";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/sign-up-form">sign up for free</Link>
      </main>
    </div>
  );
}
