import Head from "next/head";
import {Link, Button, Box} from "@mui/material";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>HomePage</Box>
    </Box>
  );
}
